"use client";

import { useMemo, useState } from "react";
import { CalendarDays, Check, CheckCircle2, ChevronDown, Clock3, LayoutDashboard, LogOut, Menu, Pencil, Plus, Send, Settings, Sparkles, Users, X } from "lucide-react";
import ProductionApp from "./production-app";

type Role = "staff" | "manager";
type View = "home" | "request" | "confirmed" | "submissions" | "schedule" | "members";
type Shift = { status: "work" | "off" | "unset"; start: string; end: string };
const names = ["山田 太郎", "田中 花子", "佐藤 一郎", "鈴木 健", "高橋 美咲", "伊藤 翔", "渡辺 彩", "中村 蓮", "小林 結衣", "加藤 大輔"];
const times = Array.from({length:27},(_,i)=>`${String(7+Math.floor(i/2)).padStart(2,"0")}:${i%2?"30":"00"}`);
const days = Array.from({length:30},(_,i)=>i+1);
const dow = ["火","水","木","金","土","日","月"];

const seedShift = (day:number):Shift => day%7===6||day%7===0 ? {status:"off",start:"07:00",end:"15:00"} : day%3===0 ? {status:"work",start:"12:00",end:"20:00"} : {status:"work",start:"07:00",end:"15:00"};

export default function App(){
  const [logged,setLogged]=useState(false); const [role,setRole]=useState<Role>("staff"); const [view,setView]=useState<View>("home");
  const [mobileNav,setMobileNav]=useState(false); const [submitted,setSubmitted]=useState(false); const [published,setPublished]=useState(false); const [reviewing,setReviewing]=useState(false);
  const [toast,setToast]=useState(""); const [shifts,setShifts]=useState<Record<number,Shift>>(()=>Object.fromEntries(days.map(d=>[d,seedShift(d)])));
  const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2600)};
  const login=(r:Role)=>{setRole(r);setView("home");setPublished(r==="staff");setReviewing(false);setLogged(true)};
  if(process.env.NEXT_PUBLIC_ENABLE_DEMO_MODE!=="true") return <ProductionApp/>;
  if(!logged) return <Login onLogin={login}/>;
  const manager=role==="manager";
  const nav = manager ? [{v:"home",l:"概要",i:LayoutDashboard},{v:"submissions",l:"提出状況",i:CheckCircle2},{v:"schedule",l:"シフト表",i:CalendarDays},{v:"members",l:"従業員",i:Users}] : [{v:"home",l:"ホーム",i:LayoutDashboard},{v:"request",l:"希望シフト",i:CalendarDays},{v:"confirmed",l:"確定シフト",i:CheckCircle2}];
  return <div className="shell">
    <aside className={mobileNav?"sidebar open":"sidebar"}><div className="brand"><span className="brandmark">S</span><span>Shiftly</span><button className="icon mobile-only" onClick={()=>setMobileNav(false)}><X/></button></div><div className="shop"><span className="shop-icon">若</span><span><b>若葉サービスステーション</b><small>店舗管理</small></span><ChevronDown/></div><nav>{nav.map(n=><button key={n.v} className={view===n.v?"active":""} onClick={()=>{setView(n.v as View);setMobileNav(false)}}><n.i/>{n.l}</button>)}</nav><div className="side-bottom"><button><Settings/>設定</button><button onClick={()=>setLogged(false)}><LogOut/>ログアウト</button><div className="profile"><div className="avatar">{manager?"店":"山"}</div><span><b>{manager?"店長 太郎":"山田 太郎"}</b><small>{manager?"管理者":"スタッフ"}</small></span></div></div></aside>
    <main><header><button className="icon mobile-only" onClick={()=>setMobileNav(true)}><Menu/></button><div className="header-title"><span>若葉サービスステーション</span><small>2026年9月のシフト</small></div><div className="role-switch"><button className={!manager?"selected":""} onClick={()=>{setRole("staff");setView("home")}}>スタッフ</button><button className={manager?"selected":""} onClick={()=>{setRole("manager");setView("home")}}>管理者</button></div><div className="header-avatar">{manager?"店":"山"}</div></header>
      <div className="content">{manager ? <Manager view={view} setView={setView} reviewing={reviewing} setReviewing={setReviewing} published={published} setPublished={setPublished} notify={notify}/> : <Staff view={view} setView={setView} shifts={shifts} setShifts={setShifts} submitted={submitted} setSubmitted={setSubmitted} published={published} notify={notify}/>}</div>
    </main>{toast&&<div className="toast"><CheckCircle2/>{toast}</div>}
  </div>
}

function Login({onLogin}:{onLogin:(r:Role)=>void}){const [email,setEmail]=useState(""); return <div className="login-page"><div className="login-art"><div className="art-brand"><span className="brandmark light">S</span>Shiftly</div><div><p className="eyebrow light-text">SMART SHIFT MANAGEMENT</p><h1>シフト作成を、<br/>もっとシンプルに。</h1><p>希望回収から確認・公開まで。<br/>毎月の手間を、ひとつの場所で。</p></div><div className="art-note"><Sparkles/><span><b>転記作業は、もう不要です</b><small>提出された希望が、そのままシフト表になります。</small></span></div></div><div className="login-panel"><div className="login-box"><div className="login-mobile-brand"><span className="brandmark">S</span>Shiftly</div><p className="eyebrow">WELCOME BACK</p><h2>ログイン</h2><p className="muted">登録されているアカウントでログインしてください。</p><label>メールアドレス<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com" type="email"/></label><label>パスワード<input placeholder="••••••••" type="password"/></label><button className="primary wide" onClick={()=>onLogin(email.includes("manager")?"manager":"staff")}>ログイン</button><div className="demo"><span>デモで試す</span><div><button onClick={()=>onLogin("staff")}>スタッフとしてログイン</button><button onClick={()=>onLogin("manager")}>管理者としてログイン</button></div></div><small className="help">ログインでお困りの場合は管理者へお問い合わせください。</small></div></div></div>}

function Staff({view,setView,shifts,setShifts,submitted,setSubmitted,published,notify}:{view:View;setView:(v:View)=>void;shifts:Record<number,Shift>;setShifts:(s:Record<number,Shift>)=>void;submitted:boolean;setSubmitted:(b:boolean)=>void;published:boolean;notify:(s:string)=>void}){
 if(view==="request") return <RequestEditor shifts={shifts} setShifts={setShifts} submitted={submitted} onSubmit={()=>{setSubmitted(true);notify("希望シフトを提出しました")}}/>;
 if(view==="confirmed") return <Confirmed shifts={shifts} published={published}/>;
 return <><div className="page-heading"><div><p className="eyebrow">STAFF HOME</p><h1>こんにちは、山田さん</h1><p>今月もおつかれさまです。</p></div><div className="date-chip"><CalendarDays/>2026年8月18日（火）</div></div>
 <section className="hero-card"><div><span className="status-pill">{submitted?"提出済み":"希望受付中"}</span><p>2026年9月</p><h2>{submitted?"希望シフトを提出済みです":"希望シフトを提出してください"}</h2><p className="muted">提出期限：2026年8月25日（火）まで</p><button className="primary" onClick={()=>setView("request")}>{submitted?<><Pencil/>確認・修正する</>:<>入力をはじめる <span>→</span></>}</button></div><div className="deadline"><span>あと</span><b>7</b><span>日</span><small>提出期限まで</small></div></section>
 <div className="two-col"><section className="card"><div className="card-head"><div className="round-icon blue"><CalendarDays/></div><div><h3>確定シフト</h3><p>公開後はこちらから確認できます</p></div></div><div className="empty-state"><div className="calendar-art"><CalendarDays/></div><b>{published?"9月のシフトが公開されました":"まだ公開されていません"}</b><p>{published?"確定した勤務日時を確認できます。":"店長がシフトを公開すると、ここから確認できます。"}</p>{published&&<button className="secondary" onClick={()=>setView("confirmed")}>確定シフトを見る</button>}</div></section><section className="card"><div className="card-head"><div className="round-icon amber"><Clock3/></div><div><h3>今後の予定</h3><p>シフト作成のスケジュール</p></div></div><div className="timeline"><div className="done"><i><Check/></i><span><b>希望受付開始</b><small>8月15日</small></span></div><div className="current"><i></i><span><b>希望提出期限</b><small>8月25日</small></span></div><div><i></i><span><b>シフト公開予定</b><small>8月28日ごろ</small></span></div></div></section></div></>;
}

function RequestEditor({shifts,setShifts,submitted,onSubmit}:{shifts:Record<number,Shift>;setShifts:(s:Record<number,Shift>)=>void;submitted:boolean;onSubmit:()=>void}){const [selected,setSelected]=useState<number[]>([]);const [bulkStart,setBulkStart]=useState("07:00");const [bulkEnd,setBulkEnd]=useState("15:00"); const work=Object.values(shifts).filter(s=>s.status==="work").length;
 const update=(d:number,p:Partial<Shift>)=>setShifts({...shifts,[d]:{...shifts[d],...p}}); const apply=()=>{const next={...shifts};selected.forEach(d=>next[d]={status:"work",start:bulkStart,end:bulkEnd});setShifts(next);setSelected([])};
 return <><div className="page-heading compact"><div><p className="eyebrow">SHIFT REQUEST</p><h1>9月の希望シフト</h1><p>勤務できる日時を入力してください。</p></div><div className="deadline-label"><Clock3/>提出期限 <b>8月25日</b></div></div><div className="progress-row"><span><b>{work}</b>日 勤務希望</span><span><b>{30-work}</b>日 休み</span><div><i style={{width:`${Math.round(Object.values(shifts).filter(s=>s.status!=="unset").length/30*100)}%`}}/></div></div>
 {selected.length>0&&<div className="bulkbar"><b>{selected.length}日を選択中</b><select value={bulkStart} onChange={e=>setBulkStart(e.target.value)}>{times.map(t=><option>{t}</option>)}</select><span>〜</span><select value={bulkEnd} onChange={e=>setBulkEnd(e.target.value)}>{times.map(t=><option>{t}</option>)}</select><button className="primary small" onClick={apply}>一括設定</button></div>}
 <section className="request-list">{days.map(d=>{const s=shifts[d];return <div className={`request-row ${dow[(d-1)%7]==="日"?"sun":""}`} key={d}><label className="select-day"><input type="checkbox" checked={selected.includes(d)} onChange={()=>setSelected(selected.includes(d)?selected.filter(x=>x!==d):[...selected,d])}/><span><b>9/{d}</b><small>{dow[(d-1)%7]}曜日</small></span></label><div className="segmented"><button className={s.status==="work"?"on":""} onClick={()=>update(d,{status:"work"})}>勤務</button><button className={s.status==="off"?"off":""} onClick={()=>update(d,{status:"off"})}>休み</button></div><div className="time-fields"><select disabled={s.status!=="work"} value={s.start} onChange={e=>update(d,{start:e.target.value})}>{times.slice(0,-1).map(t=><option>{t}</option>)}</select><span>〜</span><select disabled={s.status!=="work"} value={s.end} onChange={e=>update(d,{end:e.target.value})}>{times.slice(1).map(t=><option>{t}</option>)}</select></div></div>})}</section><div className="sticky-submit"><span><b>9月の希望</b><small>勤務 {work}日 ・ 休み {30-work}日</small></span><button className="primary" onClick={onSubmit}><Send/>{submitted?"変更を保存":"この内容で提出"}</button></div></>}

function Confirmed({shifts,published}:{shifts:Record<number,Shift>;published:boolean}){
 const [tab,setTab]=useState<"mine"|"team">("mine"); const work=days.filter(d=>shifts[d].status==="work");
 const teamData=useMemo(()=>Object.fromEntries(names.flatMap((_,ni)=>days.map(d=>{const off=(d+ni)%6===0;return [`${ni}-${d}`,{status:off?"off":"work",start:(d+ni)%3===0?"12:00":"07:00",end:(d+ni)%3===0?"20:00":"15:00",changed:false} as AdminShift]}))),[]);
 return <><div className="page-heading"><div><p className="eyebrow">CONFIRMED SHIFT</p><h1>9月の確定シフト</h1><p>公開された勤務予定です。</p></div></div>{!published?<div className="card empty-state"><CalendarDays/><h3>まだ公開されていません</h3><p>公開後にこちらから確認できます。</p></div>:<><div className="staff-shift-tabs"><button className={tab==="mine"?"active":""} onClick={()=>setTab("mine")}>自分のシフト</button><button className={tab==="team"?"active":""} onClick={()=>setTab("team")}>全体シフト</button></div>{tab==="mine"?<div className="confirmed-grid">{work.map(d=><div className="confirmed-card" key={d}><div><b>{d}</b><span>9月・{dow[(d-1)%7]}曜日</span></div><strong>{shifts[d].start} <i>—</i> {shifts[d].end}</strong></div>)}</div>:<ReadonlyTeamTimeline data={teamData}/>}</>}</>}

function ReadonlyTeamTimeline({data}:{data:Record<string,AdminShift>}){const [span,setSpan]=useState<1|3|7>(1);const [startDay,setStartDay]=useState(18);const shownDays=days.slice(startDay-1,Math.min(30,startDay-1+span));const move=(dir:number)=>setStartDay(Math.max(1,Math.min(31-span,startDay+dir*span)));return <><div className="schedule-toolbar staff-timeline-toolbar"><div className="range-nav"><button onClick={()=>move(-1)}>‹</button><b>{span===1?`9月${startDay}日（${dow[(startDay-1)%7]}）`:`9月${startDay}日〜${Math.min(30,startDay+span-1)}日`}</b><button onClick={()=>move(1)}>›</button><button className="today" onClick={()=>setStartDay(18)}>今日</button></div><div className="span-toggle">{([1,3,7] as const).map(n=><button key={n} className={span===n?"active":""} onClick={()=>{setSpan(n);setStartDay(Math.min(startDay,31-n))}}>{n===1?"1日":n===3?"3日":"1週間"}</button>)}</div></div><div className="readonly-note"><CheckCircle2/>公開済みの確定シフトです（閲覧専用）</div><ShiftGraph shownDays={shownDays} data={data} editable={false} selfIndex={0}/></>}

function Manager({view,setView,reviewing,setReviewing,published,setPublished,notify}:{view:View;setView:(v:View)=>void;reviewing:boolean;setReviewing:(b:boolean)=>void;published:boolean;setPublished:(b:boolean)=>void;notify:(s:string)=>void}){
 if(view==="submissions")return <Submissions/>; if(view==="schedule")return <Schedule published={published} onPublish={()=>{setPublished(true);notify("シフトを公開しました")}}/>; if(view==="members")return <Members notify={notify}/>;
 const status=published?"公開済み":reviewing?"確認中":"希望受付中";return <><div className="page-heading"><div><p className="eyebrow">MANAGER DASHBOARD</p><h1>9月のシフト管理</h1><p>提出状況を確認して、シフトを完成させましょう。</p></div><button className="secondary"><Plus/>次月の期間を作成</button></div><div className="stats"><div><span className="round-icon blue"><Users/></span><p>希望提出</p><b>8 <small>/ 10人</small></b><em>80%</em></div><div><span className="round-icon amber"><Clock3/></span><p>提出期限</p><b>8月25日 <small>（火）</small></b><em className="warn">あと7日</em></div><div><span className="round-icon green"><CheckCircle2/></span><p>ステータス</p><b>{status}</b><em>{published?"全員に公開中":reviewing?"シフトを編集中":"受付中"}</em></div></div>
 <section className="card action-card"><div><p className="eyebrow">NEXT ACTION</p><h2>{published?"シフトは公開されています":reviewing?"シフトを確認・調整してください":"2名がまだ提出していません"}</h2><p>{published?"公開後の修正もシフト表から行えます。":reviewing?"希望内容は仮シフトへ反映済みです。":"未提出者を確認するか、このまま受付を終了できます。"}</p></div><div>{!reviewing&&!published&&<button className="secondary" onClick={()=>setView("submissions")}>提出状況を見る</button>}<button className="primary" onClick={()=>{if(!reviewing&&!published){setReviewing(true);notify("希望受付を終了し、仮シフトを作成しました")}else setView("schedule")}}>{!reviewing&&!published?"希望受付を終了":published?"シフト表を見る":"シフトを確認"}</button></div></section>
 <div className="two-col manager-cols"><section className="card"><div className="card-title-row"><div><h3>提出状況</h3><p>8月18日 18:30 現在</p></div><button className="text-btn" onClick={()=>setView("submissions")}>すべて見る →</button></div><div className="person-list">{names.slice(0,5).map((n,i)=><div><span className="avatar small">{n[0]}</span><b>{n}</b><small className={i<4?"submitted":"pending"}>{i<4?<><Check/>提出済み</>:"未提出"}</small></div>)}</div></section><section className="card"><div className="card-title-row"><div><h3>シフト作成の流れ</h3><p>現在の進捗</p></div></div><div className="flow"><div className="done"><i><Check/></i><span><b>期間を作成</b><small>完了</small></span></div><div className={!reviewing&&!published?"current":"done"}><i>{(reviewing||published)&&<Check/>}</i><span><b>希望を回収</b><small>{reviewing||published?"完了":"進行中・8/10人"}</small></span></div><div className={reviewing?"current":published?"done":""}><i>{published&&<Check/>}</i><span><b>シフトを確認・調整</b><small>{reviewing?"進行中":"未着手"}</small></span></div><div className={published?"done":""}><i>{published&&<Check/>}</i><span><b>シフトを公開</b><small>{published?"完了":"未着手"}</small></span></div></div></section></div></>;
}

function Submissions(){return <><div className="page-heading"><div><p className="eyebrow">SUBMISSIONS</p><h1>希望提出状況</h1><p>2026年9月分・10名</p></div><button className="secondary">未提出者 2名</button></div><section className="card table-card"><table className="people-table"><thead><tr><th>従業員</th><th>メールアドレス</th><th>提出状況</th><th>提出日時</th></tr></thead><tbody>{names.map((n,i)=><tr><td><span className="avatar small">{n[0]}</span><b>{n}</b></td><td>{["yamada","tanaka","sato","suzuki","takahashi","ito","watanabe","nakamura","kobayashi","kato"][i]}@example.com</td><td><span className={i<8?"badge success":"badge neutral"}>{i<8?"提出済み":"未提出"}</span></td><td>{i<8?`8月${16+i%3}日 ${10+i}:2${i}`:"—"}</td></tr>)}</tbody></table></section></>}

type AdminShift = {status:"work"|"off";start:string;end:string;changed:boolean};
const toMinutes=(t:string)=>{const [h,m]=t.split(":").map(Number);return h*60+m};

function Schedule({published,onPublish}:{published:boolean;onPublish:()=>void}){
 const initial=useMemo(()=>Object.fromEntries(names.flatMap((_,ni)=>days.map(d=>{const off=(d+ni)%6===0;return [`${ni}-${d}`,{status:off?"off":"work",start:(d+ni)%3===0?"12:00":"07:00",end:(d+ni)%3===0?"20:00":"15:00",changed:d===8&&ni===0} as AdminShift]}))),[]);
 const [data,setData]=useState<Record<string,AdminShift>>(initial); const [mode,setMode]=useState<"table"|"graph">("table"); const [span,setSpan]=useState<1|3|7>(7); const [startDay,setStartDay]=useState(18); const [edit,setEdit]=useState<{ni:number;day:number}|null>(null);
 const shownDays=days.slice(startDay-1,Math.min(30,startDay-1+span)); const current=edit?data[`${edit.ni}-${edit.day}`]:null;
 const updateCurrent=(p:Partial<AdminShift>)=>{if(!edit)return;const k=`${edit.ni}-${edit.day}`;setData({...data,[k]:{...data[k],...p,changed:true}})};
 const move=(dir:number)=>setStartDay(Math.max(1,Math.min(31-span,startDay+dir*span)));
 return <><div className="page-heading"><div><p className="eyebrow">SHIFT TABLE</p><h1>9月のシフト表</h1><p>{mode==="table"?"セルを選択して勤務時間を調整できます。":"時間帯ごとの勤務人数と配置を確認できます。"}</p></div><button className="primary" onClick={onPublish}><Send/>{published?"変更を反映":"シフトを公開"}</button></div>
 <div className="schedule-toolbar"><div className="view-toggle"><button className={mode==="table"?"active":""} onClick={()=>setMode("table")}>一覧表示</button><button className={mode==="graph"?"active":""} onClick={()=>setMode("graph")}>グラフ表示</button></div>{mode==="graph"&&<><div className="range-nav"><button onClick={()=>move(-1)}>‹</button><b>{span===1?`9月${startDay}日（${dow[(startDay-1)%7]}）`:`9月${startDay}日〜${Math.min(30,startDay+span-1)}日`}</b><button onClick={()=>move(1)}>›</button><button className="today" onClick={()=>setStartDay(18)}>今日</button></div><div className="span-toggle">{([1,3,7] as const).map(n=><button className={span===n?"active":""} onClick={()=>{setSpan(n);setStartDay(Math.min(startDay,31-n))}}>{n===1?"1日":n===3?"3日":"1週間"}</button>)}</div></>}</div>
 {mode==="table"?<><div className="legend"><span><i className="dot blue-dot"/>勤務</span><span><i className="dot gray-dot"/>休み</span><span><i className="dot amber-dot"/>希望から変更済み</span></div><section className="schedule-wrap"><table className="schedule-table"><thead><tr><th>従業員</th>{days.map(d=><th key={d}><b>{d}</b><small>{dow[(d-1)%7]}</small></th>)}</tr></thead><tbody>{names.map((n,ni)=><tr key={n}><th><span className="avatar tiny">{n[0]}</span>{n.replace(" ","")}</th>{days.map(d=>{const s=data[`${ni}-${d}`];return <td key={d} onClick={()=>setEdit({ni,day:d})} className={s.changed?"changed":""}>{s.status==="off"?<span className="off-cell">休</span>:<span><b>{s.start.replace(":00","")}-{s.end.replace(":00","")}</b>{s.changed&&<small>変更済</small>}</span>}</td>})}</tr>)}</tbody></table></section></>:<ShiftGraph shownDays={shownDays} data={data} onEdit={(ni,day)=>setEdit({ni,day})}/>}
 {edit&&current&&<div className="modal-bg" onClick={()=>setEdit(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="icon close" onClick={()=>setEdit(null)}><X/></button><p className="eyebrow">SHIFT EDIT</p><h2>{names[edit.ni]}</h2><p>9月{edit.day}日（{dow[(edit.day-1)%7]}）</p><label>勤務区分<div className="segmented full"><button className={current.status==="work"?"on":""} onClick={()=>updateCurrent({status:"work"})}>勤務</button><button className={current.status==="off"?"off":""} onClick={()=>updateCurrent({status:"off"})}>休み</button></div></label><div className="modal-times"><label>開始<select disabled={current.status==="off"} value={current.start} onChange={e=>updateCurrent({start:e.target.value})}>{times.slice(0,-1).map(t=><option key={t}>{t}</option>)}</select></label><span>〜</span><label>終了<select disabled={current.status==="off"} value={current.end} onChange={e=>updateCurrent({end:e.target.value})}>{times.slice(1).map(t=><option key={t}>{t}</option>)}</select></label></div><button className="primary wide" onClick={()=>setEdit(null)}>保存する</button></div></div>}</>}

function ShiftGraph({shownDays,data,onEdit,editable=true,selfIndex}:{shownDays:number[];data:Record<string,AdminShift>;onEdit?:(ni:number,day:number)=>void;editable?:boolean;selfIndex?:number}){
 const hours=Array.from({length:14},(_,i)=>i+7); const colors=["#4776d9","#5f8f80","#9b72b0","#c47a62","#6686a5","#a98b4f","#557dbe","#8a756e","#4f929b","#806fa8"];
 return <div className={`graph-days ${editable?"":"readonly"}`}>{shownDays.map(day=>{const staff=names.map((name,ni)=>({name,ni,shift:data[`${ni}-${day}`]}));const counts=hours.slice(0,-1).map(h=>staff.filter(x=>x.shift.status==="work"&&toMinutes(x.shift.start)<=h*60&&h*60<toMinutes(x.shift.end)).length);const max=Math.max(1,...counts);return <section className="day-chart" key={day}><div className="day-chart-head"><div><b>9月{day}日</b><span>{dow[(day-1)%7]}曜日</span></div><p>ピーク <b>{max}人</b></p></div><div className="chart-scroll"><div className="chart-inner"><div className="hour-axis"><span></span>{hours.map(h=><i key={h}>{h}</i>)}</div><div className="coverage"><div className="coverage-label">勤務人数</div><div className="coverage-bars">{counts.map((count,i)=><div className="count-column" key={i}><b style={{bottom:`${10+count/max*46}px`}}>{count}</b><i style={{height:`${count/max*46}px`}}/></div>)}</div></div><div className="staff-bars">{staff.map(({name,ni,shift})=>{const mine=ni===selfIndex;const click=editable&&onEdit?()=>onEdit(ni,day):undefined;return <div className={`staff-lane ${mine?"my-lane":""}`} key={name}><button type="button" disabled={!editable} className="staff-name" onClick={click}><span style={{background:colors[ni]}}/>{name.replace(" ","")}{mine&&<em>自分</em>}</button><div className="lane-track">{shift.status==="work"?<button type="button" disabled={!editable} className={`shift-bar ${editable&&shift.changed?"modified":""} ${mine?"my-shift":""}`} onClick={click} style={{left:`${(toMinutes(shift.start)-420)/780*100}%`,width:`${(toMinutes(shift.end)-toMinutes(shift.start))/780*100}%`,background:colors[ni]}}><span>{shift.start}–{shift.end}</span>{editable&&shift.changed&&<i>変更済</i>}</button>:<button type="button" disabled={!editable} className="off-label" onClick={click}>休</button>}</div></div>})}</div></div></div></section>})}</div>}

function Members({notify}:{notify:(s:string)=>void}){return <><div className="page-heading"><div><p className="eyebrow">TEAM MEMBERS</p><h1>従業員管理</h1><p>アカウントと権限を管理します。</p></div><button className="primary" onClick={()=>notify("従業員追加フォームを開きました")}><Plus/>従業員を追加</button></div><section className="card table-card"><table className="people-table"><thead><tr><th>氏名</th><th>メールアドレス</th><th>権限</th><th>状態</th><th></th></tr></thead><tbody>{names.map((n,i)=><tr><td><span className="avatar small">{n[0]}</span><b>{n}</b></td><td>staff{i+1}@example.com</td><td>{i===0?"manager":"staff"}</td><td><span className="badge success">有効</span></td><td><button className="icon"><Pencil/></button></td></tr>)}</tbody></table></section></>}
